ARG REPO=mcr.microsoft.com/dotnet/aspnet
ARG TAG=5.0-alpine
FROM $REPO:$TAG
EXPOSE 80 443
WORKDIR /app
COPY src/EventManager.Identity.Admin.Api/bin/Release/net5.0/. .
ENTRYPOINT ["dotnet", "EventManager.Identity.Admin.Api.exe"]
