version: '3'

services:
  em_identity_web:
   environment:
      - ASPNETCORE_ENVIRONMENT=Production
   build:
      dockerfile: src/EventManager.Identity.Admin/Dockerfile.release  
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  em_identity_api:
   environment:
      - ASPNETCORE_ENVIRONMENT=Production
   build:
      dockerfile: src/EventManager.Identity.Admin.Api/Dockerfile.release  
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  em_identity_tokenservice:
   environment:
      - ASPNETCORE_ENVIRONMENT=Production
   build:
      dockerfile: src/EventManager.Identity.STS.Identity/Dockerfile.release  
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
