name: Build and Deploy EventManager
on:
  push:
    branches: [ DBChangeOver ]
  pull_request:
    branches:  [ DBChangeOver ]
jobs:
    setup-environment:
        name: Setup WebApp Build Environment
        runs-on: windows-latest
        env:
            DOTNET_VERSION: '3.1.301'   
            NODE_VERSION: '12.19.0'
        steps:
            # Get latest code
            - name: Clone WebApp Repository
                uses: actions/checkout@v2

            # Install .NET Core
            - name: Install .NET Core 
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}  

            # Install NodeJS
            - name: Install NodeJS 
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ env.NODE_VERSION }}

    build-and-test:
        name: Restore Build and Test WebApp
        needs: setup-environment
        runs-on: windows-latest
        steps:
            # Run dotnet restore
            - name: Restore WebApp Dependencies
                run: dotnet restore

            # Run dotnet build 
            - name: Build WebApp
                run: dotnet build --configuration Release --no-restore

            # Run dotnet test
            #- name: Test WebApp
            #   run: dotnet test --no-restore --verbosity normal
  
    publish-and-deploy:
        name: Publish and Deploy WebApp
        needs: build-and-test
        runs-on: windows-latest
        steps:
            # Run dotnet publish
            - name: Publish WebApp
                run: dotnet publish -c Release -o './webapp'
      
            # Deploy to Azure Web apps
            - name: Deploy WebApp
                uses: azure/webapps-deploy@v2
                with: 
                    app-name: 'EM-WebUI'
                    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
                    package: ./webapp

  

   
          
   
