name: Build and Deploy EventManager
on:
  push:
    branches: [ master ]
  pull_request:
    branches:  [ master ]
jobs:
  create-and-deploy:
    name: DevOps Pipeline
    runs-on: windows-latest
    env:
        AZURE_WEBAPP_NAME: EM-WebUI
        DOTNET_VERSION: '5.0.100'   
        NODE_VERSION: '12.19.0'
    steps:
    # Get latest code
    - name: Clone Repository
      uses: actions/checkout@v2

    # Install .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}  

    # Install NodeJS
    - name: Install NodeJS 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    # Run dotnet estore
    - name: Restore Dependencies
      run: dotnet restore

    # Run dotnet build 
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run dotnet test
    #- name: Test WebApp
    #  run: dotnet test --no-restore --verbosity normal
          
    # Run dotnet publish
    - name: Publish
      run: dotnet publish -c Release -o './webapp'
      
   # Deploy to Azure Web apps
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: './webapp'
